name: geo-app

channels:
  - conda-forge

dependencies:

  - python=3.11

  - streamlit
  - streamlit-folium
  - folium

  - numpy
  - pandas

  - matplotlib

  - rasterio
  - geopandas
  - shapely
  - pyproj
  - pyogrio

  - branca

  - pillow

  - xarray
  - netcdf4

  - scipy

  - pip

  - pip:
      - global-land-mask
